-- Variantes base de las 15 velas por 6 aromas (90 combinaciones).
-- No establece tamaños ni presentaciones aún no confirmados.
-- Zero stock, nullable price, inactive status: no public sale is enabled.
-- Re-runnable: existing business edits are preserved.
INSERT OR IGNORE INTO store_variants
  (id, product_id, sku, label, aroma_id, price_cop, status, on_hand, reserved, allow_made_to_order, preparation_days)
VALUES
  ('variant-titina-natilla', 'product-titina', 'CHV2-titina-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-titina-cafe', 'product-titina', 'CHV2-titina-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-titina-chocolate', 'product-titina', 'CHV2-titina-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-titina-lulada', 'product-titina', 'CHV2-titina-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-titina-frutos-del-bosque', 'product-titina', 'CHV2-titina-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-titina-uva', 'product-titina', 'CHV2-titina-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-churras-queridas-natilla', 'product-churras-queridas', 'CHV2-churras-queridas-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-churras-queridas-cafe', 'product-churras-queridas', 'CHV2-churras-queridas-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-churras-queridas-chocolate', 'product-churras-queridas', 'CHV2-churras-queridas-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-churras-queridas-lulada', 'product-churras-queridas', 'CHV2-churras-queridas-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-churras-queridas-frutos-del-bosque', 'product-churras-queridas', 'CHV2-churras-queridas-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-churras-queridas-uva', 'product-churras-queridas', 'CHV2-churras-queridas-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chuscas-natilla', 'product-chuscas', 'CHV2-chuscas-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chuscas-cafe', 'product-chuscas', 'CHV2-chuscas-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chuscas-chocolate', 'product-chuscas', 'CHV2-chuscas-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chuscas-lulada', 'product-chuscas', 'CHV2-chuscas-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chuscas-frutos-del-bosque', 'product-chuscas', 'CHV2-chuscas-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chuscas-uva', 'product-chuscas', 'CHV2-chuscas-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-regia-natilla', 'product-regia', 'CHV2-regia-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-regia-cafe', 'product-regia', 'CHV2-regia-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-regia-chocolate', 'product-regia', 'CHV2-regia-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-regia-lulada', 'product-regia', 'CHV2-regia-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-regia-frutos-del-bosque', 'product-regia', 'CHV2-regia-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-regia-uva', 'product-regia', 'CHV2-regia-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-serendipia-natilla', 'product-serendipia', 'CHV2-serendipia-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-serendipia-cafe', 'product-serendipia', 'CHV2-serendipia-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-serendipia-chocolate', 'product-serendipia', 'CHV2-serendipia-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-serendipia-lulada', 'product-serendipia', 'CHV2-serendipia-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-serendipia-frutos-del-bosque', 'product-serendipia', 'CHV2-serendipia-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-serendipia-uva', 'product-serendipia', 'CHV2-serendipia-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-candor-natilla', 'product-candor', 'CHV2-candor-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-candor-cafe', 'product-candor', 'CHV2-candor-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-candor-chocolate', 'product-candor', 'CHV2-candor-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-candor-lulada', 'product-candor', 'CHV2-candor-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-candor-frutos-del-bosque', 'product-candor', 'CHV2-candor-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-candor-uva', 'product-candor', 'CHV2-candor-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chia-natilla', 'product-chia', 'CHV2-chia-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chia-cafe', 'product-chia', 'CHV2-chia-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chia-chocolate', 'product-chia', 'CHV2-chia-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chia-lulada', 'product-chia', 'CHV2-chia-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chia-frutos-del-bosque', 'product-chia', 'CHV2-chia-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chia-uva', 'product-chia', 'CHV2-chia-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-grande-natilla', 'product-quimera-grande', 'CHV2-quimera-grande-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-grande-cafe', 'product-quimera-grande', 'CHV2-quimera-grande-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-grande-chocolate', 'product-quimera-grande', 'CHV2-quimera-grande-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-grande-lulada', 'product-quimera-grande', 'CHV2-quimera-grande-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-grande-frutos-del-bosque', 'product-quimera-grande', 'CHV2-quimera-grande-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-grande-uva', 'product-quimera-grande', 'CHV2-quimera-grande-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-pequena-natilla', 'product-quimera-pequena', 'CHV2-quimera-pequena-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-pequena-cafe', 'product-quimera-pequena', 'CHV2-quimera-pequena-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-pequena-chocolate', 'product-quimera-pequena', 'CHV2-quimera-pequena-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-pequena-lulada', 'product-quimera-pequena', 'CHV2-quimera-pequena-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-pequena-frutos-del-bosque', 'product-quimera-pequena', 'CHV2-quimera-pequena-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-quimera-pequena-uva', 'product-quimera-pequena', 'CHV2-quimera-pequena-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chata-natilla', 'product-chata', 'CHV2-chata-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chata-cafe', 'product-chata', 'CHV2-chata-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chata-chocolate', 'product-chata', 'CHV2-chata-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chata-lulada', 'product-chata', 'CHV2-chata-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chata-frutos-del-bosque', 'product-chata', 'CHV2-chata-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-chata-uva', 'product-chata', 'CHV2-chata-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-gnomo-natilla', 'product-gnomo', 'CHV2-gnomo-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-gnomo-cafe', 'product-gnomo', 'CHV2-gnomo-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-gnomo-chocolate', 'product-gnomo', 'CHV2-gnomo-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-gnomo-lulada', 'product-gnomo', 'CHV2-gnomo-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-gnomo-frutos-del-bosque', 'product-gnomo', 'CHV2-gnomo-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-gnomo-uva', 'product-gnomo', 'CHV2-gnomo-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-carinito-natilla', 'product-carinito', 'CHV2-carinito-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-carinito-cafe', 'product-carinito', 'CHV2-carinito-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-carinito-chocolate', 'product-carinito', 'CHV2-carinito-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-carinito-lulada', 'product-carinito', 'CHV2-carinito-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-carinito-frutos-del-bosque', 'product-carinito', 'CHV2-carinito-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-carinito-uva', 'product-carinito', 'CHV2-carinito-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-antojitos-natilla', 'product-antojitos', 'CHV2-antojitos-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-antojitos-cafe', 'product-antojitos', 'CHV2-antojitos-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-antojitos-chocolate', 'product-antojitos', 'CHV2-antojitos-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-antojitos-lulada', 'product-antojitos', 'CHV2-antojitos-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-antojitos-frutos-del-bosque', 'product-antojitos', 'CHV2-antojitos-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-antojitos-uva', 'product-antojitos', 'CHV2-antojitos-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-foforro-natilla', 'product-foforro', 'CHV2-foforro-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-foforro-cafe', 'product-foforro', 'CHV2-foforro-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-foforro-chocolate', 'product-foforro', 'CHV2-foforro-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-foforro-lulada', 'product-foforro', 'CHV2-foforro-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-foforro-frutos-del-bosque', 'product-foforro', 'CHV2-foforro-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-foforro-uva', 'product-foforro', 'CHV2-foforro-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-calderito-natilla', 'product-calderito', 'CHV2-calderito-natilla', 'Natilla', 'aroma-natilla', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-calderito-cafe', 'product-calderito', 'CHV2-calderito-cafe', 'Café', 'aroma-cafe', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-calderito-chocolate', 'product-calderito', 'CHV2-calderito-chocolate', 'Chocolate', 'aroma-chocolate', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-calderito-lulada', 'product-calderito', 'CHV2-calderito-lulada', 'Lulada', 'aroma-lulada', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-calderito-frutos-del-bosque', 'product-calderito', 'CHV2-calderito-frutos-del-bosque', 'Frutos del bosque', 'aroma-frutos-del-bosque', NULL, 'inactive', 0, 0, 1, 14),
  ('variant-calderito-uva', 'product-calderito', 'CHV2-calderito-uva', 'Uva', 'aroma-uva', NULL, 'inactive', 0, 0, 1, 14);
